# Configurations
title:            Template de apuntes de programaciÃ³n
longtitle:        Template apuntes
author:           wilderPariona
email:            wilder.pariona.27@unsch.edu.pe
description: >
  Template base jekyll para apuntes basado en jekyll-gitbook

version:          1.0
gitbook_version:  3.2.3

url:              'https://jhonpariona.github.io'
baseurl:          '/template-apuntes'
rss:              RSS

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
